### ISSUE TITLE
Deep Learning and Lens-finding

### ISSUE THREAD

**Issue by linan7788626** [linan7788626/hackday02172017#1]
@EiffL @NobleKennamer Hi guys, check this out, we will post the results here. :-)

**Comment by linan7788626** [comment]
Hi @EiffL ,

Here is an example of the name of a lensed images.
lensed_9996_264.263367853_0.941831769034_171.051217387_0.534_3.84560673085_imgs.fits.gz

The values here are:

lensed _ [ID] _ [Velocity Dispersion of the lens] _ [Eillipticity of the lens] _ [Orientation of the lens] _ [Redshift of the lens] _ [Magnification of the lensed images] _imgs.fits.gz

Please let me know if you need any further information. 

Thanks,
Nan

**Comment by EiffL** [comment]
Here is how to read the result file:
```
from astropy.table  import Table
t = Table.read('lsst_catalog_test.hdf5')
```

**Comment by EiffL** [comment]
Here are some true positive:
![image](https://cloud.githubusercontent.com/assets/861591/23087311/0f21679e-f528-11e6-99e9-7ecf8b85f17a.png)

False Positives:
![image](https://cloud.githubusercontent.com/assets/861591/23087325/23ab95d6-f528-11e6-8e8e-96d14fd2bd14.png)

**Comment by NobleKennamer** [comment]
Shallow Conv Net: AUC 0.80

![image](https://cloud.githubusercontent.com/assets/6298530/23088031/b6ff837e-f52d-11e6-9763-512e03c3f354.png)

**Comment by EiffL** [comment]
Here is the comparison of ROC curves using the resnet with the Single and Stack images:
![image](https://cloud.githubusercontent.com/assets/861591/23087655/c34f3942-f52a-11e6-8809-598768dfbbe1.png)

**Comment by EiffL** [comment]
Here is the corresponding Purity Completeness
 
![image](https://cloud.githubusercontent.com/assets/861591/23087758/a2871e22-f52b-11e6-83ed-71ca21c39ad5.png)

**Comment by linan7788626** [comment]
![figure_1](https://cloud.githubusercontent.com/assets/1016652/23088273/d0bd288c-f52f-11e6-8b16-721df58520c3.png)

**Comment by linan7788626** [comment]
@EiffL @NobleKennamer @hsybetty Hi Hackers, Hopefully, we all enjoyed the past fantastic hackday time. It is very nice to meet you and work with you all. I will close this issue now, but let's keep in touch for the future collaborations. Have a nice weekend and see you next time. :-)
